"""
Database seeding functions
Populates initial data like advice templates
"""

from sqlalchemy.orm import Session
import logging
import json

logger = logging.getLogger("chatbot.database.seed")


def seed_advice_templates(db: Session) -> None:
    """
    Seed expert-reviewed advice templates into the database

    Args:
        db: Database session
    """
    # Import here to avoid circular dependency
    from models.safety import AdviceTemplate

    # Check if templates already exist
    existing_count = db.query(AdviceTemplate).count()
    if existing_count > 0:
        logger.info(f"Advice templates already seeded ({existing_count} templates)")
        return

    logger.info("Seeding advice templates...")

    templates = [
        # School Stress
        {
            "category": "school_stress",
            "keywords": json.dumps(["test", "homework", "grade", "study", "exam", "project"]),
            "template": "Hey {name}, I know tests can feel really overwhelming! Here's what might help: 1) Break your studying into small chunks - like 20 minutes at a time. 2) Try teaching the material to someone else (even a stuffed animal!). 3) Make sure you get good sleep the night before. You've got this! And remember, one test doesn't define you. Want to talk about what you're most worried about?",
            "min_friendship_level": 1,
            "expert_reviewed": True,
        },
        {
            "category": "school_stress",
            "keywords": json.dumps(["homework", "assignment", "project", "due"]),
            "template": "Homework piling up? I get it, {name}. Try this: make a list of everything you need to do, then tackle the easiest thing first. That little win will give you momentum! Break big projects into tiny steps. And don't forget to take breaks - your brain needs them! You're doing great just by working on it.",
            "min_friendship_level": 2,
            "expert_reviewed": True,
        },
        # Friend Conflict - Arguments and Fights
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "argument", "fight", "mad at me", "ignoring", "yelled"]),
            "template": "Friend arguments are really tough, {name}. Here's something that might help: try to see it from their perspective too. Maybe they didn't mean to hurt you, or maybe they're going through something hard. When you're both calm, you could say something like 'I felt hurt when...' instead of 'You did...' That makes it easier to talk about. And hey, real friends can work through disagreements. Give it a little time, okay?",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "conflict", "argument", "communication"]),
        },
        # Friend Conflict - Being Excluded
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["left out", "excluded", "ignored", "not invited", "didn't include"]),
            "template": "Feeling left out really stings, {name}. I'm sorry you're going through this. Sometimes people don't realize they're leaving someone out, or maybe they had limited space. It doesn't mean you're not important! You could try talking to your friend directly about how you feel, or focus on other friendships too. You're an awesome person and deserve friends who include you!",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "exclusion", "hurt_feelings", "social"]),
        },
        # Friend Conflict - Betrayal and Gossip
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "told", "secret", "gossip", "talked about me", "betrayed", "trust"]),
            "template": "Having a friend share your secret or talk about you behind your back really hurts, {name}. That's a big betrayal of trust. It's okay to feel angry and sad about this. You could tell them directly: 'I trusted you with that, and it hurt when you shared it.' Then see how they respond. Sometimes people make mistakes and genuinely apologize. But if someone keeps breaking your trust, they might not be a good friend right now. You deserve friends who keep your secrets safe.",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "betrayal", "trust", "gossip", "secrets"]),
        },
        # Friend Conflict - Jealousy
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["jealous", "envy", "friend", "other friends", "attention", "popularity"]),
            "template": "Jealousy in friendships is actually pretty normal, {name}, even though it doesn't feel good. Maybe you're worried about losing your friend, or you wish you had what they have. Here's the thing: friendship isn't a competition! Your friend having other friends doesn't mean they like you less. And if you're jealous of something they have, remember - everyone has different strengths. Try focusing on what makes YOUR friendship special. Can you talk to them about feeling left out?",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "gentle",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "jealousy", "insecurity", "emotions"]),
        },
        # Friend Conflict - Making New Friends
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "new friend", "new friends", "replacing", "don't want"]),
            "template": "When your friend makes new friends, it can feel scary, {name}. You might worry they'll forget about you or replace you. But here's the truth: people can have multiple friends! It's actually healthy to have different friends for different things. Instead of competing with the new friend, try getting to know them too. Or talk to your friend: 'I miss hanging out just us sometimes. Can we plan something?' Your friendship can grow even stronger when you both have other friends too!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "encouraging",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "new_friends", "insecurity", "change"]),
        },
        # Friend Conflict - Apologizing
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["sorry", "apologize", "my fault", "I messed up", "hurt my friend"]),
            "template": "It takes courage to realize you hurt someone and want to apologize, {name}. That's really mature! A good apology has three parts: 1) Say you're sorry. 2) Say what you did wrong ('I'm sorry I said mean things'). 3) Say what you'll do differently ('I'll think before I speak next time'). Then give them time to accept it - they might still be hurt. But a real apology shows you care about the friendship. You're doing the right thing!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "apology", "accountability", "repair"]),
        },
        # Friend Conflict - Forgiving
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["forgive", "friend hurt me", "should I forgive", "still mad", "let it go"]),
            "template": "Forgiveness is tricky, {name}. It doesn't mean pretending nothing happened or letting someone keep hurting you. It means: 'I'm choosing not to stay angry about this.' Ask yourself: Did they apologize? Do they understand what they did? Are they trying to change? If yes, then forgiving might help your friendship heal. If they keep doing the same hurtful things, you might need distance instead. Forgiveness is for YOU as much as them - it helps you stop carrying around all that hurt. Take your time deciding.",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "questioning",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "forgiveness", "boundaries", "healing"]),
        },
        # Friend Conflict - Peer Pressure from Friends
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "pressure", "make me", "want me to", "don't want to", "forcing"]),
            "template": "Real friends don't pressure you to do things that make you uncomfortable, {name}. If someone is pushing you to do something you don't want to do - whether it's something dangerous, mean to others, or just not your thing - that's not okay. You can say: 'No thanks, I'm not into that' or 'That doesn't feel right to me.' If they keep pushing or make fun of you, they're not being a good friend. Friends respect your choices! It's always okay to say no.",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "peer_pressure", "boundaries", "assertiveness"]),
        },
        # Friend Conflict - Friend Moving Away
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "moving", "moving away", "leaving", "far away", "different school"]),
            "template": "Having a friend move away is really hard, {name}. It's okay to feel sad, angry, or even a bit lost. But here's the good news: friendship doesn't have to end because of distance! You can video chat, text, send letters or packages, play online games together. Make plans to visit if possible. Yes, it'll be different, but you can stay connected. And who knows? You might make new friends where you are, while keeping your special friendship with them too. The best friendships survive distance.",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "loss", "distance", "change", "sadness"]),
        },
        # Friend Conflict - Growing Apart
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "different", "don't have", "common", "changed", "growing apart", "not close"]),
            "template": "Sometimes friendships change as people grow, {name}, and that's actually pretty normal - even if it's sad. Maybe you used to love the same things, but now your interests are different. That doesn't mean anyone did anything wrong! You can: 1) Try to find new things you BOTH like, 2) Appreciate the friendship for what it was, or 3) Be okay with being less close while still being friendly. Not every friendship lasts forever, and that's okay. The good ones might come back around later, or you'll make new friends who match who you're becoming.",
            "min_friendship_level": 5,
            "min_age": 10,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "change", "growth", "interests", "acceptance"]),
        },
        # Friend Conflict - One-Sided Friendship
        {
            "category": "friendship",
            "subcategory": "friend_conflict",
            "keywords": json.dumps(["friend", "one-sided", "always me", "never", "effort", "reach out", "initiate"]),
            "template": "It's exhausting when you're always the one reaching out, planning things, or making an effort, isn't it {name}? You deserve friends who try as hard as you do! Sometimes people don't realize they're not reciprocating - you could try saying 'Hey, I feel like I'm always the one texting first. Can we both try to stay in touch?' See how they respond. If nothing changes, it might be time to put your energy into friendships that go both ways. You shouldn't have to do all the work!",
            "min_friendship_level": 4,
            "min_age": 10,
            "max_age": 14,
            "tone": "validating",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["friendship", "imbalance", "effort", "reciprocity"]),
        },
        # Performance Anxiety - Presentations and Public Speaking
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["nervous", "scared", "worried", "anxious", "presentation", "public speaking", "class talk"]),
            "template": "Being nervous is totally normal, {name} - even adults get nervous! Try this: take slow, deep breaths (breathe in for 4, hold for 4, out for 4). Remember that everyone else has probably felt this way too. And here's a secret: a little nervousness can actually help you do better! It means you care. You're going to be great!",
            "min_friendship_level": 2,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "presentations", "public_speaking"]),
        },
        # Performance Anxiety - Test Anxiety
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["test", "exam", "quiz", "nervous", "anxious", "worried", "fail", "blank"]),
            "template": "Test anxiety is SO common, {name}. Your brain is trying to protect you, but it's going overboard! Here's what helps: 1) Study in chunks - don't cram the night before. 2) Practice deep breathing before the test. 3) Read through the whole test first, do the easy questions, then go back. 4) Remember: one test doesn't define you! If your mind goes blank, take three deep breaths and try the next question. You know more than your anxiety is telling you!",
            "min_friendship_level": 2,
            "min_age": 8,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "practical",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "tests", "academic", "stress"]),
        },
        # Performance Anxiety - Sports Performance
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["sports", "game", "match", "nervous", "pressure", "mess up", "choke", "perform"]),
            "template": "Feeling nervous before a game is your body getting ready to compete, {name}! Channel that energy: 1) Visualize yourself succeeding - see it in your mind. 2) Focus on your preparation, not the outcome. 3) Use a routine (same warm-up, same pre-game ritual). 4) Remember your training - your body knows what to do! Don't let fear of messing up stop you from trying. Even pros make mistakes. The difference is they keep going. You've got this!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "sports", "competition", "athletics"]),
        },
        # Performance Anxiety - Musical/Artistic Performances
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["recital", "concert", "performance", "audition", "stage fright", "music", "dance", "play"]),
            "template": "Stage fright before a recital or performance is totally normal, {name}! Even famous performers get it. Try this: 1) Practice so much that your body can do it on autopilot. 2) Perform for family/friends first to get used to an audience. 3) Focus on sharing your art, not being perfect. 4) Pick one friendly face in the audience to perform for. Remember: the audience wants you to succeed! They're rooting for you. One mistake won't ruin everything - just keep going!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "arts", "music", "stage_fright"]),
        },
        # Performance Anxiety - Tryouts and Auditions
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["tryout", "audition", "try out", "making the team", "nervous", "rejection", "not good enough"]),
            "template": "Tryouts can feel like so much pressure, {name}! Remember: you're not trying to be perfect, you're trying to show what you CAN do. Tips: 1) Prepare as much as possible. 2) Get there early so you're not rushed. 3) Focus on YOUR performance, not comparing yourself to others. 4) Remind yourself: 'I'm here to do my best, that's all I can control.' Not making it doesn't mean you're not good - sometimes it's about fit or timing. Trying is the bravest part!",
            "min_friendship_level": 3,
            "min_age": 9,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "tryouts", "auditions", "rejection"]),
        },
        # Performance Anxiety - Speaking in Class
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["raise hand", "answer", "speaking", "class", "wrong answer", "embarrassed", "call on"]),
            "template": "Being nervous to speak up in class is super common, {name}. Here's the thing: asking questions and participating helps you learn! Tips: 1) Start small - answer when you're 100% sure. 2) Remember that 'wrong' answers help the whole class learn. 3) Teachers appreciate effort more than perfection. 4) Your classmates are probably too worried about themselves to judge you. Everyone feels this way sometimes. The more you practice speaking up, the easier it gets. You're braver than you think!",
            "min_friendship_level": 2,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "gentle",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "classroom", "participation", "academic"]),
        },
        # Performance Anxiety - Fear of Failure
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["fail", "failure", "not good enough", "scared", "mess up", "disappoint", "lose"]),
            "template": "Fear of failure can be paralyzing, {name}, but here's a secret: failure is how we learn! Every successful person has failed many times. What if instead of 'What if I fail?' you asked 'What if I succeed?' or 'What will I learn?' You can: 1) Break big goals into tiny steps. 2) Focus on effort, not just results. 3) Remember that trying and 'failing' is better than never trying. 4) Celebrate attempts, not just wins. You're capable of more than you think. Failure isn't the opposite of success - it's part of it!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "failure", "fear", "self_doubt"]),
        },
        # Performance Anxiety - Perfectionism
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["perfect", "perfectionist", "not good enough", "never satisfied", "has to be perfect", "mistake"]),
            "template": "Wanting to do well is great, {name}, but perfectionism can actually hold you back! Perfect doesn't exist - there's always something to improve. Here's healthier thinking: 1) Aim for 'good enough' instead of perfect. 2) Set realistic goals. 3) Celebrate progress, not just the final product. 4) Remember: mistakes are proof you're trying something hard! Ask yourself: 'Am I doing my best?' If yes, that's enough. Your worth isn't based on being perfect. You're already enough just as you are!",
            "min_friendship_level": 4,
            "min_age": 10,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "perfectionism", "self_criticism", "standards"]),
        },
        # Performance Anxiety - Competition Nerves
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["competition", "compete", "nervous", "pressure", "win", "lose", "tournament"]),
            "template": "Competition nerves are your body's way of saying 'this matters to me!' {name}. Use that energy: 1) Focus on doing YOUR best, not beating others. 2) Have a pre-competition routine that calms you. 3) Remember why you started - for fun, for challenge, for growth. 4) Win or lose, you're learning valuable skills. The point isn't always winning - it's improving, trying hard, and enjoying the challenge. You've already won by showing up and competing. Be proud of that!",
            "min_friendship_level": 3,
            "min_age": 9,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "competition", "pressure", "sports"]),
        },
        # Performance Anxiety - Overthinking
        {
            "category": "emotional",
            "subcategory": "performance_anxiety",
            "keywords": json.dumps(["overthinking", "thinking too much", "can't stop thinking", "worried", "what if", "anxious"]),
            "template": "When you're overthinking before a performance, your brain is trying to prepare for every possibility, {name}. But it's making things worse! Here's how to break the cycle: 1) Write down your worries, then close the notebook - they're recorded, now move on. 2) Do something physical - jump, run, dance to interrupt the thoughts. 3) Focus on what you CAN control (your preparation) not what you can't (the outcome). 4) Use a mantra: 'I'm prepared. I'll do my best. That's enough.' Your mind is powerful - redirect it!",
            "min_friendship_level": 3,
            "min_age": 10,
            "max_age": 14,
            "tone": "practical",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["anxiety", "performance", "overthinking", "worry", "mental_health"]),
        },
        # Family Issues - General Family Conflict
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["parent", "sibling", "mom", "dad", "brother", "sister", "family", "argue"]),
            "template": "Family stuff can be complicated, {name}. It's okay to have mixed feelings about family members. If something is bothering you, try talking to a parent or trusted adult when everyone is calm. Use 'I feel' statements like 'I feel sad when...' Sometimes families need help communicating, and that's okay! Would talking to a school counselor help?",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "gentle",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "conflict", "communication", "relationships"]),
        },
        # Family Issues - Sibling Rivalry
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["sibling", "brother", "sister", "annoying", "fight", "mean", "bothering"]),
            "template": "Siblings can be SO annoying sometimes, right {name}? It's normal to fight with brothers and sisters - you're learning how to share space and attention. But here's the thing: they're not going anywhere, so finding ways to get along helps everyone. Try: 1) Take a break when you're annoyed. 2) Tell them how you feel ('I get upset when you touch my stuff'). 3) Find things you both enjoy. 4) Remember: sometimes they're annoying because they want your attention. You don't have to be best friends, but you can learn to coexist!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "siblings", "rivalry", "conflict"]),
        },
        # Family Issues - Parents Fighting
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["parents", "fighting", "arguing", "yelling", "divorce", "scared", "worried"]),
            "template": "Hearing your parents fight can be really scary, {name}. I want you to know: it's not your fault, and you can't fix it. Adults sometimes disagree, and that's their issue to work out. What you can do: 1) Go to your room if it's too loud or scary. 2) Talk to a trusted adult about how you feel. 3) Remember that parents can argue and still love each other (and you!). If you're worried about divorce or separation, it's okay to ask your parents about it when things are calm. You deserve to feel safe at home.",
            "min_friendship_level": 5,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "parents", "conflict", "safety", "worry"]),
        },
        # Family Issues - Feeling Misunderstood
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["parents", "don't understand", "listen", "misunderstood", "care", "get me"]),
            "template": "Feeling like your parents don't understand you is really frustrating, {name}. Sometimes adults forget what it was like to be your age! Try this: pick a calm time and say 'Can we talk? I need you to understand something.' Then explain your feelings without blaming ('I feel...' instead of 'You always...'). Ask them to just listen first. If talking face-to-face is hard, try writing a letter. And remember: even when they don't understand everything, they do care about you. Sometimes understanding takes time and lots of tries!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "communication", "understanding", "frustration"]),
        },
        # Family Issues - Unfair Rules
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["rules", "unfair", "strict", "not fair", "allowed", "can't", "restrictions"]),
            "template": "Rules that feel unfair are super frustrating, {name}! Here's the thing: sometimes rules ARE unfair, and sometimes they just feel that way. You can: 1) Ask your parents to explain WHY they have that rule. Understanding helps! 2) Suggest a compromise ('What if I...?'). 3) Show you're responsible with smaller things to earn more trust. 4) Accept that some rules won't change, even if you disagree. Calmly discussing rules works better than arguing or breaking them. Your parents are trying to keep you safe, even when it doesn't feel like it!",
            "min_friendship_level": 3,
            "min_age": 9,
            "max_age": 14,
            "tone": "practical",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "rules", "boundaries", "fairness", "autonomy"]),
        },
        # Family Issues - Divorce and Separation
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["divorce", "separation", "separated", "splitting up", "leaving", "moving out"]),
            "template": "Divorce or separation is a really big, hard thing, {name}. First: this is NOT your fault. Nothing you did caused this. Your parents' relationship problems are between them. It's okay to feel sad, angry, confused, or even relieved - all feelings are valid. Things that help: 1) Talk about your feelings with someone you trust. 2) Ask your parents questions when you have them. 3) Keep routines when you can. 4) Remember: both parents can still love you even if they don't love each other. This is a huge change, and it's okay to need help dealing with it. You're going to be okay.",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "divorce", "separation", "major_change", "grief"]),
        },
        # Family Issues - Blended Families
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["step", "stepparent", "stepmom", "stepdad", "stepbrother", "stepsister", "blended", "new family"]),
            "template": "Adjusting to a blended family is HARD, {name}. You're dealing with new people, new rules, sharing a parent... it's a lot! It's okay if you don't instantly love your step-parent or step-siblings. Relationships take time. You can: 1) Be polite and give it a chance. 2) Set boundaries about your space and belongings. 3) Talk to your bio parent about your feelings. 4) Find common ground with step-siblings. You don't have to replace anyone - your heart can expand. But you're allowed to take your time adjusting. This is a big change for everyone.",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "blended_family", "step_family", "adjustment", "change"]),
        },
        # Family Issues - Parent Expectations and Pressure
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["pressure", "expectations", "grades", "achieve", "disappoint", "good enough", "perfect"]),
            "template": "Feeling pressure from your parents to be perfect or achieve more can be exhausting, {name}. Here's what helps: 1) Have an honest conversation: 'I'm trying my best, but this pressure makes me feel...' 2) Ask what success really means to them - maybe you're misunderstanding. 3) Show them your effort, not just results. 4) Set your own realistic goals. Remember: your worth isn't based on your achievements. Parents sometimes push because they care, but they need to know when it's too much. You're allowed to have limits!",
            "min_friendship_level": 4,
            "min_age": 10,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "pressure", "expectations", "achievement", "stress"]),
        },
        # Family Issues - Can't Talk to Parents
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["can't talk", "won't listen", "too busy", "don't care", "ignore", "communication"]),
            "template": "When it feels like your parents won't listen or are too busy, that really hurts, {name}. Try these strategies: 1) Schedule a specific time: 'Can we talk after dinner?' 2) Start with 'This is really important to me.' 3) Be direct about what you need: 'I need advice' or 'I just need you to listen.' 4) If one parent is easier to talk to, start there. 5) Write them a letter if talking is too hard. If you truly can't reach your parents, talk to another trusted adult - teacher, counselor, family member. You deserve to be heard!",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "practical",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "communication", "neglect", "listening", "connection"]),
        },
        # Family Issues - Comparing to Siblings
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["favorite", "sibling", "compare", "better", "golden child", "love more", "unfair"]),
            "template": "Feeling like your parents favor a sibling over you really stings, {name}. That hurts! Sometimes it's real favoritism, sometimes it just feels that way because siblings need different things. What you can do: 1) Talk to your parents: 'Sometimes I feel like you love [sibling] more because...' Be specific. 2) Remember: love isn't a competition. They can love you both differently. 3) Focus on YOUR relationship with your parents, not the comparison. 4) Recognize your own unique strengths. If this is a serious ongoing issue, talking to a counselor might help. You deserve to feel valued for who YOU are!",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "favoritism", "siblings", "comparison", "self_worth"]),
        },
        # Family Issues - Privacy and Boundaries
        {
            "category": "family",
            "subcategory": "family_issues",
            "keywords": json.dumps(["privacy", "room", "space", "boundaries", "respect", "alone time", "knock"]),
            "template": "Wanting privacy doesn't mean you're hiding something, {name} - it means you're growing up! Everyone needs personal space. Try talking to your family: 'I need some alone time in my room sometimes. Can we set up a rule where people knock?' Explain it's not about them - it's about you needing space to think, relax, or just be. Respect goes both ways: if you want privacy, respect others' space too. If they're worried you're hiding something, show them you're trustworthy in other ways. Privacy is a normal part of growing up!",
            "min_friendship_level": 4,
            "min_age": 10,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["family", "privacy", "boundaries", "autonomy", "growing_up"]),
        },
        # Self Confidence - General Self-Doubt
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["not good at", "bad at", "everyone else", "I can't", "terrible", "awful"]),
            "template": "Hey {name}, everyone is good at different things! The stuff you find hard might be easy for others, but I bet there are things you're great at that others struggle with. What matters is that you're trying and learning. Making mistakes is how we get better! What's one thing you ARE good at? Let's celebrate that!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "self_doubt", "abilities", "growth_mindset"]),
        },
        # Self Confidence - Comparing to Others
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["compare", "better than me", "not as good", "everyone is", "wish I was"]),
            "template": "Comparing yourself to others is a tough habit, {name}. But here's the thing: you're on your own unique journey! Everyone learns and grows at different speeds. Instead of comparing, try competing with yourself - are you better than you were last month? Last year? That's what really matters. You're doing amazing just by being you!",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "validating",
            "response_style": "encouraging",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "comparison", "self_worth", "uniqueness"]),
        },
        # Self Confidence - Body Image and Appearance
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["ugly", "look bad", "appearance", "how I look", "body", "fat", "skinny", "short", "tall"]),
            "template": "How you feel about your appearance is really personal, {name}, and I'm glad you're talking about it. Here's the truth: bodies come in all shapes and sizes, and they ALL deserve respect - including yours! Your body is doing amazing things every day - growing, healing, moving. What you look like is just one tiny part of who you are. What makes you YOU is your kindness, humor, creativity, and all the other awesome things you bring to the world. If mean thoughts about your body are really bothering you, talking to a trusted adult can help!",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "gentle",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "body_image", "appearance", "self_acceptance"]),
        },
        # Self Confidence - Academic Abilities
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["not smart", "dumb", "stupid", "bad at school", "failing", "bad grades"]),
            "template": "I hear you feeling down about school, {name}. But listen: grades don't measure how smart or valuable you are! Everyone has subjects they find easier and harder. Maybe you're amazing at creative stuff, or solving problems, or being kind - those are all forms of intelligence! If you're struggling in school: 1) Ask for help - that's what smart people do! 2) Try different study methods. 3) Give yourself credit for effort, not just results. 4) Remember that struggling means you're learning! You're smarter than you think.",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "academic", "intelligence", "school", "growth_mindset"]),
        },
        # Self Confidence - Social Skills and Fitting In
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["don't fit in", "weird", "awkward", "no friends", "don't belong", "outcast"]),
            "template": "Feeling like you don't fit in is one of the hardest feelings, {name}. I'm really sorry you're feeling this way. Here's something important: 'fitting in' often means hiding who you really are. But 'belonging' means being accepted for who you actually are! The right friends will like the real you - quirks and all. What makes you different might feel weird now, but it's actually what makes you special. Keep being authentically you, and you'll find your people. They're out there looking for someone just like you!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "social", "belonging", "fitting_in", "authenticity"]),
        },
        # Self Confidence - Fear of Trying New Things
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["scared to try", "embarrassed", "what if I fail", "look stupid", "mess up"]),
            "template": "Being scared to try new things because you might fail or look silly is SO normal, {name}. But here's the secret: everyone who's good at something was bad at it first! Nobody is watching you as closely as you think - they're too worried about themselves. And you know what? Trying and 'failing' is way better than never trying at all. That's how you learn and grow! Start small: try something new with just one friend, or practice alone first. Every expert was once a beginner. You've got to be brave for just a few seconds - then you're already doing it!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "fear", "trying_new_things", "courage", "growth"]),
        },
        # Self Confidence - Not Being Good Enough
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["not good enough", "never enough", "disappointing", "let everyone down", "failure"]),
            "template": "That feeling of not being 'good enough' is really painful, {name}. I want you to hear this: you ARE enough, exactly as you are right now. Your worth isn't based on what you achieve or how you perform. You're valuable just because you exist! Sometimes we set impossible standards for ourselves, or we think we have to earn love and acceptance. But you don't. Ask yourself: would you judge a friend this harshly? Probably not! Try giving yourself the same kindness you'd give them. You're doing better than you think, and you're absolutely good enough.",
            "min_friendship_level": 5,
            "min_age": 9,
            "max_age": 14,
            "tone": "gentle",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "self_worth", "enough", "self_compassion"]),
        },
        # Self Confidence - Being Picked Last
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["picked last", "nobody wants me", "not chosen", "left out", "not wanted"]),
            "template": "Being picked last really stings, {name}. It can make you feel like nobody wants you around, but that's not true! Often people pick their close friends first, or the most skilled players - it's not about you being unwanted, it's about them being strategic or going with who they know. Your worth isn't determined by being picked first in PE! You have so much to offer. Focus on: being a good teammate, improving your skills just for yourself, and remembering that being picked last says nothing about how awesome you are as a person. The right people will always want you on their team!",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "rejection", "social", "sports", "belonging"]),
        },
        # Self Confidence - Learning from Mistakes
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["made a mistake", "messed up", "did something wrong", "feel stupid", "embarrassed"]),
            "template": "Making mistakes feels terrible in the moment, {name}, but here's the truth: mistakes are proof you're trying something challenging! Every single successful person has made tons of mistakes - that's literally how they got good. What matters isn't whether you make mistakes (you will!), it's what you do next. Can you: 1) Learn from it? 2) Apologize if you hurt someone? 3) Try again? 4) Be kind to yourself? Mistakes don't make you stupid or bad - they make you human and brave for trying. Tomorrow is a fresh start!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "encouraging",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "mistakes", "growth_mindset", "resilience", "self_compassion"]),
        },
        # Self Confidence - Unique Interests
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["different interests", "nobody likes", "weird hobby", "nerdy", "into different things"]),
            "template": "Having different interests than other kids can make you feel alone, {name}. But here's the cool thing: your unique interests are what make you YOU! Being 'different' or 'nerdy' about something just means you're passionate and deep - that's awesome! The kids who make fun of your interests? They're probably just uncomfortable with anything unfamiliar. Don't dim your light to fit in! Keep loving what you love. The internet has communities of people who share your interests. And someday, being passionate and unique will be one of your greatest strengths. Never apologize for what makes you come alive!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "validating",
            "response_style": "encouraging",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "interests", "uniqueness", "authenticity", "passion"]),
        },
        # Self Confidence - Standing Up for Yourself
        {
            "category": "emotional",
            "subcategory": "self_confidence",
            "keywords": json.dumps(["can't stand up", "scared to speak", "let people walk over", "pushover", "voice"]),
            "template": "Learning to stand up for yourself takes practice and courage, {name}. It's not about being mean or aggressive - it's about respecting yourself enough to use your voice! Start small: 1) Practice saying 'I don't like that' or 'Please stop' in a mirror. 2) Use 'I' statements: 'I feel...' instead of 'You always...' 3) Stand tall and make eye contact. 4) It's okay if your voice shakes - that's just courage fighting fear! Remember: your needs and feelings matter just as much as everyone else's. You deserve to be heard and respected. The more you practice, the easier it gets!",
            "min_friendship_level": 4,
            "min_age": 10,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["self_confidence", "assertiveness", "boundaries", "self_advocacy", "voice"]),
        },
        # Boredom
        {
            "category": "boredom",
            "keywords": json.dumps(["bored", "nothing to do", "no fun"]),
            "template": "Bored? Let's fix that, {name}! Here are some ideas: 1) Try creating something - draw, write, build. 2) Learn a new skill from YouTube. 3) Go outside and explore. 4) Read a book or start a new series. 5) Help someone with something. Sometimes boredom means your brain is ready for a new challenge! What sounds interesting to you?",
            "min_friendship_level": 1,
            "expert_reviewed": True,
        },
        # Homeschool Stress - Social Isolation
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "lonely", "no friends", "isolated", "miss school"]),
            "template": "Hey {name}, I hear you - being homeschooled can sometimes feel lonely. But here's the good news: there are lots of ways to connect! Try joining homeschool co-ops, sports teams, clubs, or online communities for kids who share your interests. Libraries often have programs too! You could also invite kids from your neighborhood to hang out. Being homeschooled doesn't mean being alone - it just means finding friends in different places!",
            "min_friendship_level": 2,
            "min_age": 8,
            "max_age": 14,
            "tone": "supportive",
            "response_style": "encouraging",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "social_isolation", "loneliness"]),
        },
        # Homeschool Stress - Self-Motivation
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "focus", "distracted", "motivation", "procrastinate"]),
            "template": "Staying focused at home is hard, {name} - even adults struggle with this! Try these tricks: 1) Create a special study spot that's ONLY for schoolwork. 2) Use a timer - work for 25 minutes, break for 5. 3) Start with the hardest subject when your brain is fresh. 4) Give yourself small rewards for finishing tasks. 5) Put away your phone and other distractions. You're basically the boss of your own learning - pretty cool, right?",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "practical",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "self_discipline", "focus", "motivation"]),
        },
        # Homeschool Stress - Parent as Teacher
        {
            "category": "family",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "parent", "mom", "dad", "teacher", "frustrated"]),
            "template": "Having your parent as your teacher can be tricky sometimes, {name}. It's hard when the person who makes you dinner is also the one explaining math! If you're feeling frustrated, try this: take a break when things get tense, come back when everyone is calmer. Remember, your parents are learning how to teach just like you're learning the subjects. It's okay to say 'Can we try a different way?' or 'I need a break.' You're both doing your best!",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "parent_conflict", "family_stress"]),
        },
        # Homeschool Stress - Missing Traditional School
        {
            "category": "emotional",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "miss", "regular school", "traditional school", "wish"]),
            "template": "It's totally okay to miss parts of traditional school, {name}. Maybe you miss having lots of classmates, or the school lunch, or special activities. Those feelings are valid! Homeschooling is different, not better or worse - just different. Talk to your parents about what you miss most - maybe you can find ways to get some of those experiences through clubs, classes, or events. And remember, homeschooling has cool perks too - like learning in your pajamas or going on field trips on random Tuesdays!",
            "min_friendship_level": 3,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "nostalgia", "school_experience"]),
        },
        # Homeschool Stress - Structure and Independence
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "schedule", "routine", "structure", "organize"]),
            "template": "Finding the right balance between freedom and structure is one of the trickiest parts of homeschooling, {name}! Here's what might help: create a daily routine (but keep it flexible), use a planner to track assignments, set small goals for each day. Too much freedom can feel overwhelming, but too much structure can feel boring. Work with your parents to find YOUR perfect balance. What works for other homeschoolers might not work for you - and that's okay!",
            "min_friendship_level": 3,
            "min_age": 9,
            "max_age": 14,
            "tone": "practical",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "time_management", "organization"]),
        },
        # Homeschool Stress - Distractions at Home
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "distracted", "siblings", "noise", "interruptions"]),
            "template": "I get it, {name} - when your classroom is also your home, distractions are everywhere! Your siblings, pets, the TV, your bed calling your name... Try this: 1) Find a quiet spot just for school (even a corner works!). 2) Use headphones with focus music or white noise. 3) Set 'do not disturb' times with your family. 4) Put away toys and games during school hours. Sometimes you might need to speak up: 'I need quiet time to focus right now.' It's okay to protect your learning space!",
            "min_friendship_level": 2,
            "min_age": 8,
            "max_age": 13,
            "tone": "supportive",
            "response_style": "practical",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "distractions", "focus", "environment"]),
        },
        # Homeschool Stress - Being Different
        {
            "category": "social",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "different", "weird", "explain", "don't understand"]),
            "template": "When people ask about homeschooling and don't get it, that can feel awkward, right {name}? Here's the thing: different doesn't mean wrong! You could say something simple like 'I do school at home with my parents. It's pretty cool because...' and share what YOU like about it. Not everyone will understand, and that's okay. You don't have to convince anyone. The people who matter will accept you no matter where you go to school. You're unique - and that's actually awesome!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "social_acceptance", "being_different"]),
        },
        # Homeschool Stress - Time Management
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "time", "deadline", "finish", "behind"]),
            "template": "Time management without bells and schedules can be tough, {name}! Try this system: 1) Write down all your tasks for the week. 2) Estimate how long each will take (then add a little extra - we're all optimistic!). 3) Schedule the hardest stuff for when you have the most energy. 4) Use timers to stay on track. 5) Build in buffer time for the unexpected. Remember, homeschooling is flexible - if something takes longer than planned, you can adjust! The goal is learning, not racing the clock.",
            "min_friendship_level": 3,
            "min_age": 10,
            "max_age": 14,
            "tone": "practical",
            "response_style": "direct",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "time_management", "organization", "deadlines"]),
        },
        # Homeschool Stress - Missing Activities
        {
            "category": "emotional",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "miss", "activities", "sports", "clubs", "events"]),
            "template": "Missing out on school dances, sports teams, or clubs can feel really sad, {name}. I'm sorry you're feeling this way. Good news though - you can still do many of these things! Look for: community sports leagues, music or art classes, 4-H clubs, Scout groups, homeschool co-op activities, library programs, volunteer opportunities. Many communities have versions of school activities that are open to everyone! Talk to your parents about what you miss most - they might be able to help you find similar experiences.",
            "min_friendship_level": 4,
            "min_age": 8,
            "max_age": 14,
            "tone": "empathetic",
            "response_style": "supportive",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "extracurricular", "social_activities"]),
        },
        # Homeschool Stress - Learning Style Mismatch
        {
            "category": "school",
            "subcategory": "homeschool_stress",
            "keywords": json.dumps(["homeschool", "don't understand", "learning", "teaching", "curriculum"]),
            "template": "If the way your parents are teaching something isn't clicking for you, {name}, that doesn't mean you're not smart! Everyone learns differently. Some people need to see things, some need to hear them, some need to DO them. Try telling your parents: 'This isn't making sense to me. Can we try it a different way?' There are SO many resources - videos, apps, books, hands-on activities. One of the cool things about homeschooling is you can customize how you learn. You're allowed to ask for what you need!",
            "min_friendship_level": 4,
            "min_age": 9,
            "max_age": 14,
            "tone": "encouraging",
            "response_style": "validating",
            "expert_reviewed": True,
            "context_tags": json.dumps(["homeschool", "learning_style", "communication", "education"]),
        },
    ]

    # Create template objects
    for template_data in templates:
        template = AdviceTemplate(**template_data)
        db.add(template)

    # Commit all templates
    db.commit()

    logger.info(f"Seeded {len(templates)} advice templates")
